spring.application.name=k-review
spring.datasource.url=jdbc:postgresql://localhost:5432/kreview
spring.datasource.username=wol
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
gemini.api.key=${GEMINI_API_KEY}
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000
