spring.application.name=k-review
spring.datasource.url=jdbc:postgresql://localhost:5432/kreview
spring.datasource.username=wol
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true